version: "3.8"
services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
    networks:
      - backend
  api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - oracle
    ports:
    - "8080:8080"
    - "5005:5005"
    networks:
      - backend

networks:
  backend: